{
	"version": 1663191252,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/pista-sheet0.png",
		"images/pista-sheet1.png",
		"images/vehiculo_rojo-sheet0.png",
		"images/vehiculo_rojo-sheet1.png",
		"images/vehiculo_azul-sheet0.png",
		"images/vehiculo_azul-sheet1.png",
		"images/vehiculo_negro-sheet0.png",
		"images/vehiculo_negro-sheet1.png",
		"images/vehiculo_amarillo-sheet0.png",
		"images/vehiculo_amarillo-sheet1.png",
		"images/vehiculo_verde-sheet0.png",
		"images/vehiculo_verde-sheet1.png",
		"images/fuera_de_pista-sheet0.png",
		"images/fuera_de_pista-sheet1.png",
		"images/protecciones-sheet0.png",
		"images/pistatierra-sheet0.png",
		"images/pistaagua-sheet0.png",
		"images/pistaagua-sheet1.png",
		"images/pistaagua-sheet2.png",
		"images/cmdcomenzar-sheet0.png",
		"images/piloto_amarillo-sheet0.png",
		"images/piloto_azul-sheet0.png",
		"images/piloto_negro-sheet0.png",
		"images/piloto_rojo-sheet0.png",
		"images/piloto_verde-sheet0.png",
		"images/pasto.png",
		"images/paso_pasto_arena.png",
		"images/arena.png",
		"images/paso_tierra_arena.png",
		"images/llantas.png",
		"images/tiledbackground.png",
		"images/agua.png",
		"images/paso_tierra_pasto.png",
		"images/pista_asfalto.png",
		"images/borde_pista.png",
		"images/pista_tierra.png",
		"images/borde_pista_tierra.png",
		"images/pista_.png",
		"images/velocidad_alta-sheet0.png",
		"images/velocidad_media-sheet0.png",
		"images/velocidad_baja-sheet0.png",
		"images/meta-sheet0.png",
		"images/objetos_solidos.png",
		"images/checkpoint0-sheet0.png",
		"images/contador-sheet0.png",
		"images/contador-sheet1.png",
		"images/contador-sheet2.png",
		"images/cartel_vueltas-sheet0.png",
		"images/aceite-sheet0.png",
		"images/luces_azul-sheet0.png",
		"images/luces-sheet0.png",
		"images/luz_suelo-sheet0.png",
		"images/posiciónes-sheet0.png",
		"images/ganaste_perdiste-sheet0.png",
		"images/ultima_vuelta-sheet0.png",
		"images/cmdjugar-sheet0.png",
		"images/musica_si-sheet0.png",
		"images/musica_no-sheet0.png",
		"images/cmdopciones-sheet0.png",
		"images/cmdvolver_menu-sheet0.png",
		"images/total-sheet0.png",
		"images/cmdsalir-sheet0.png",
		"images/volver_menu-sheet0.png",
		"images/volver_a_intentar-sheet0.png",
		"images/siguiente_nivel-sheet0.png",
		"images/marco_selección-sheet0.png",
		"images/inicio-sheet0.png",
		"images/pausa-sheet0.png",
		"images/sonido-sheet0.png",
		"images/musica-sheet0.png",
		"images/marco_musica-sheet0.png",
		"images/humo-sheet0.png",
		"images/humo-sheet1.png",
		"images/humo-sheet2.png",
		"images/transformación-sheet0.png",
		"images/transformación-sheet1.png",
		"images/transformación-sheet2.png",
		"images/creditos-sheet0.png",
		"images/felicitaciones-sheet0.png",
		"images/eres_el_mas_rapido-sheet0.png",
		"images/instagram-sheet0.png",
		"images/nivel_1-sheet0.png",
		"media/000952351_prev (online-audio-converter.com).ogg",
		"media/kart-start-mario (online-audio-converter.com).ogg",
		"media/sonido motor.ogg",
		"media/till-dawn-evgeny-bardyuzha.ogg",
		"media/formula 1 theme live in concert by brian tyler (online-audio-converter.com).ogg",
		"media/lil-nas-x-montero-call-me-by-your-name-lyrics (online-audio-converter.com).ogg",
		"media/masked-wolf-astronaut-in-the-ocean (online-audio-converter.com).ogg",
		"media/meduza-goodboys-piece-of-your-heart-visualizer (online-audio-converter.com).ogg",
		"media/paradise-meduza-ft-dermot-kennedy-subtitulado-espanol (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}